# Generated by Django 5.1.2 on 2024-11-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_profile_alter_question_id_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
