# Generated by Django 5.1.2 on 2024-11-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.answer'),
        ),
    ]
