# Generated by Django 5.1.2 on 2024-11-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_question_id_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
