# Generated by Django 5.1.2 on 2024-11-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_question_id_answer_answer_id_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id_tags',
            new_name='tags',
        ),
    ]
