# Generated by Django 5.1.2 on 2024-11-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_answerquestion_likequestion_delete_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerQuestion',
            new_name='LikeAnswer',
        ),
    ]
