# Generated by Django 5.1.2 on 2024-11-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_answerquestion_likeanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_answered',
            new_name='answered',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='id_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('answer', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('question', 'user')},
        ),
        migrations.CreateModel(
            name='DislikeAnswer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.profile')),
            ],
            options={
                'unique_together': {('answer', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DislikeQuestion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.profile')),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
    ]
