# Generated by Django 5.1.2 on 2024-11-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_is_answered_answer_answered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
