# Generated by Django 5.1.2 on 2024-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_question_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tagquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
