# Generated by Django 5.1.2 on 2024-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_rename_id_user_question_user_alter_tagquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikeanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dislikequestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='likeanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='likequestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
